### ISSUE TITLE
Cannot Find Module "Google APIs"

### ISSUE THREAD

**Issue by MinhajMoin** [AhsanSN/Meme-Viewer#2]
![wfa](https://user-images.githubusercontent.com/21280679/41781396-d2c9ae0e-7650-11e8-9319-1f0777157ff3.PNG)
When I type `npm start` on the cmd, it fails to find googleapis module even though the folder for it is in the node_modules folder.

**Comment by MinhajMoin** [comment]
![image](https://user-images.githubusercontent.com/21280679/41781766-c8e032b8-7651-11e8-8b2d-0ce234a551ce.png)
![image](https://user-images.githubusercontent.com/21280679/41781782-d474cba2-7651-11e8-9a47-8a5229864aca.png)
I removed the node_modules folder, and did another `npm install`. These errors are being shown now.

**Comment by AhsanSN** [comment]
Hello Minhaj! Congratulations on opening your first issue. Follow the following steps to solve the problem.
1) restore the `node_modules ` folder.
2) run `npm install googleapis -g`
3) run `npm start`

The application should start then.
